CRITICAL - 2025-07-23 10:26:59 --> ErrorException: Undefined variable $newFileName
[Method: POST, Route: api/attendance/checkin]
in APPPATH\Controllers\api\Attendance.php on line 91.
 1 APPPATH\Controllers\api\Attendance.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $newFileName', 'E:\\laragon\\www\\apici\\app\\Controllers\\api\\Attendance.php', 91)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 10:27:09 --> ErrorException: Undefined variable $newFileName
[Method: POST, Route: api/attendance/checkin]
in APPPATH\Controllers\api\Attendance.php on line 91.
 1 APPPATH\Controllers\api\Attendance.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $newFileName', 'E:\\laragon\\www\\apici\\app\\Controllers\\api\\Attendance.php', 91)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 10:30:14 --> ErrorException: Undefined variable $newFileName
[Method: POST, Route: api/attendance/checkin]
in APPPATH\Controllers\api\Attendance.php on line 91.
 1 APPPATH\Controllers\api\Attendance.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $newFileName', 'E:\\laragon\\www\\apici\\app\\Controllers\\api\\Attendance.php', 91)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:15:39 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:15:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:15:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:39\', \'2025-07-23\', \'1753244139_902994ba38a48d00e648.jpg\', \'2025-07-23 11:15:39\', \'2025-07-23 11:15:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:39\', \'2025-07-23\', \'1753244139_902994ba38a48d00e648.jpg\', \'2025-07-23 11:15:39\', \'2025-07-23 11:15:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:15:39 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:39\', \'2025-07-23\', \'1753244139_902994ba38a48d00e648.jpg\', \'2025-07-23 11:15:39\', \'2025-07-23 11:15:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:39\', \'2025-07-23\', \'1753244139_902994ba38a48d00e648.jpg\', \'2025-07-23 11:15:39\', \'2025-07-23 11:15:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:39\', \'2025-07-23\', \'1753244139_902994ba38a48d00e648.jpg\', \'2025-07-23 11:15:39\', \'2025-07-23 11:15:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:15:45 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:15:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:15:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:45\', \'2025-07-23\', \'1753244145_e7eea648c9e180cdb1ca.jpg\', \'2025-07-23 11:15:45\', \'2025-07-23 11:15:45\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:45\', \'2025-07-23\', \'1753244145_e7eea648c9e180cdb1ca.jpg\', \'2025-07-23 11:15:45\', \'2025-07-23 11:15:45\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:15:45 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:45\', \'2025-07-23\', \'1753244145_e7eea648c9e180cdb1ca.jpg\', \'2025-07-23 11:15:45\', \'2025-07-23 11:15:45\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:45\', \'2025-07-23\', \'1753244145_e7eea648c9e180cdb1ca.jpg\', \'2025-07-23 11:15:45\', \'2025-07-23 11:15:45\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431994\', \'106.7888005\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:15:45\', \'2025-07-23\', \'1753244145_e7eea648c9e180cdb1ca.jpg\', \'2025-07-23 11:15:45\', \'2025-07-23 11:15:45\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:16:23 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:16:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:16:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:23\', \'2025-07-23\', \'1753244183_bfd8dfaca53df4a6a6b1.jpg\', \'2025-07-23 11:16:23\', \'2025-07-23 11:16:23\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:23\', \'2025-07-23\', \'1753244183_bfd8dfaca53df4a6a6b1.jpg\', \'2025-07-23 11:16:23\', \'2025-07-23 11:16:23\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:16:23 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:23\', \'2025-07-23\', \'1753244183_bfd8dfaca53df4a6a6b1.jpg\', \'2025-07-23 11:16:23\', \'2025-07-23 11:16:23\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:23\', \'2025-07-23\', \'1753244183_bfd8dfaca53df4a6a6b1.jpg\', \'2025-07-23 11:16:23\', \'2025-07-23 11:16:23\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:23\', \'2025-07-23\', \'1753244183_bfd8dfaca53df4a6a6b1.jpg\', \'2025-07-23 11:16:23\', \'2025-07-23 11:16:23\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:16:39 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:16:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:16:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:39\', \'2025-07-23\', \'1753244199_27552ed64257438463a0.jpg\', \'2025-07-23 11:16:39\', \'2025-07-23 11:16:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:39\', \'2025-07-23\', \'1753244199_27552ed64257438463a0.jpg\', \'2025-07-23 11:16:39\', \'2025-07-23 11:16:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:16:39 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:39\', \'2025-07-23\', \'1753244199_27552ed64257438463a0.jpg\', \'2025-07-23 11:16:39\', \'2025-07-23 11:16:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:39\', \'2025-07-23\', \'1753244199_27552ed64257438463a0.jpg\', \'2025-07-23 11:16:39\', \'2025-07-23 11:16:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432024\', \'106.7887948\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:16:39\', \'2025-07-23\', \'1753244199_27552ed64257438463a0.jpg\', \'2025-07-23 11:16:39\', \'2025-07-23 11:16:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:21:08 --> ErrorException: Undefined variable $newFileName
[Method: POST, Route: api/attendance/checkin]
in APPPATH\Controllers\api\Attendance.php on line 91.
 1 APPPATH\Controllers\api\Attendance.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $newFileName', 'E:\\laragon\\www\\apici\\app\\Controllers\\api\\Attendance.php', 91)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:22:13 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(63): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:22:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(63): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:22:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432069\', \'106.7888341\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:22:13\', \'2025-07-23\', \'1753244533_e320362aa02ec0261e51.jpg\', \'2025-07-23 11:22:13\', \'2025-07-23 11:22:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432069\', \'106.7888341\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:22:13\', \'2025-07-23\', \'1753244533_e320362aa02ec0261e51.jpg\', \'2025-07-23 11:22:13\', \'2025-07-23 11:22:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(63): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:22:13 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432069\', \'106.7888341\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:22:13\', \'2025-07-23\', \'1753244533_e320362aa02ec0261e51.jpg\', \'2025-07-23 11:22:13\', \'2025-07-23 11:22:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432069\', \'106.7888341\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:22:13\', \'2025-07-23\', \'1753244533_e320362aa02ec0261e51.jpg\', \'2025-07-23 11:22:13\', \'2025-07-23 11:22:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432069\', \'106.7888341\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:22:13\', \'2025-07-23\', \'1753244533_e320362aa02ec0261e51.jpg\', \'2025-07-23 11:22:13\', \'2025-07-23 11:22:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(63): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:24:36 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 11:28:36 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:28:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:28:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:36\', \'2025-07-23\', \'1753244915_d0f5966b016fe0cf0565.jpg\', \'2025-07-23 11:28:36\', \'2025-07-23 11:28:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:36\', \'2025-07-23\', \'1753244915_d0f5966b016fe0cf0565.jpg\', \'2025-07-23 11:28:36\', \'2025-07-23 11:28:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:28:36 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:36\', \'2025-07-23\', \'1753244915_d0f5966b016fe0cf0565.jpg\', \'2025-07-23 11:28:36\', \'2025-07-23 11:28:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:36\', \'2025-07-23\', \'1753244915_d0f5966b016fe0cf0565.jpg\', \'2025-07-23 11:28:36\', \'2025-07-23 11:28:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:36\', \'2025-07-23\', \'1753244915_d0f5966b016fe0cf0565.jpg\', \'2025-07-23 11:28:36\', \'2025-07-23 11:28:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:28:41 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:28:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:28:41 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:41\', \'2025-07-23\', \'1753244921_4aca74477e42458da355.jpg\', \'2025-07-23 11:28:41\', \'2025-07-23 11:28:41\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:41\', \'2025-07-23\', \'1753244921_4aca74477e42458da355.jpg\', \'2025-07-23 11:28:41\', \'2025-07-23 11:28:41\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:28:42 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:41\', \'2025-07-23\', \'1753244921_4aca74477e42458da355.jpg\', \'2025-07-23 11:28:41\', \'2025-07-23 11:28:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:41\', \'2025-07-23\', \'1753244921_4aca74477e42458da355.jpg\', \'2025-07-23 11:28:41\', \'2025-07-23 11:28:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431933\', \'106.7887867\', \'100, Jalan Damai, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:28:41\', \'2025-07-23\', \'1753244921_4aca74477e42458da355.jpg\', \'2025-07-23 11:28:41\', \'2025-07-23 11:28:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:31:05 --> ErrorException: Cannot declare class App\Database\Migrations\CreateOvertimeSubmissionsTable, because the name is already in use
[Method: CLI, Route: migrate]
in APPPATH\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-07-23 11:33:04 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 11:33:20 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:33:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:33:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431978\', \'106.7888036\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:33:20\', \'2025-07-23\', \'1753245200_4d322eaa7c2823f77f1c.jpg\', \'2025-07-23 11:33:20\', \'2025-07-23 11:33:20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431978\', \'106.7888036\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:33:20\', \'2025-07-23\', \'1753245200_4d322eaa7c2823f77f1c.jpg\', \'2025-07-23 11:33:20\', \'2025-07-23 11:33:20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:33:21 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431978\', \'106.7888036\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:33:20\', \'2025-07-23\', \'1753245200_4d322eaa7c2823f77f1c.jpg\', \'2025-07-23 11:33:20\', \'2025-07-23 11:33:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431978\', \'106.7888036\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:33:20\', \'2025-07-23\', \'1753245200_4d322eaa7c2823f77f1c.jpg\', \'2025-07-23 11:33:20\', \'2025-07-23 11:33:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3431978\', \'106.7888036\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:33:20\', \'2025-07-23\', \'1753245200_4d322eaa7c2823f77f1c.jpg\', \'2025-07-23 11:33:20\', \'2025-07-23 11:33:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:35:05 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 11:48:17 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:48:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:48:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:48:17\', \'2025-07-23\', \'1753246097_39e6c0c919352d21bb6a.jpg\', \'2025-07-23 11:48:17\', \'2025-07-23 11:48:17\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:48:17\', \'2025-07-23\', \'1753246097_39e6c0c919352d21bb6a.jpg\', \'2025-07-23 11:48:17\', \'2025-07-23 11:48:17\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:48:17 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:48:17\', \'2025-07-23\', \'1753246097_39e6c0c919352d21bb6a.jpg\', \'2025-07-23 11:48:17\', \'2025-07-23 11:48:17\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:48:17\', \'2025-07-23\', \'1753246097_39e6c0c919352d21bb6a.jpg\', \'2025-07-23 11:48:17\', \'2025-07-23 11:48:17\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:48:17\', \'2025-07-23\', \'1753246097_39e6c0c919352d21bb6a.jpg\', \'2025-07-23 11:48:17\', \'2025-07-23 11:48:17\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:49:13 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:49:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:49:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:49:13\', \'2025-07-23\', \'1753246153_b7184b8a026508a5ebb7.jpg\', \'2025-07-23 11:49:13\', \'2025-07-23 11:49:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:49:13\', \'2025-07-23\', \'1753246153_b7184b8a026508a5ebb7.jpg\', \'2025-07-23 11:49:13\', \'2025-07-23 11:49:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:49:13 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:49:13\', \'2025-07-23\', \'1753246153_b7184b8a026508a5ebb7.jpg\', \'2025-07-23 11:49:13\', \'2025-07-23 11:49:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:49:13\', \'2025-07-23\', \'1753246153_b7184b8a026508a5ebb7.jpg\', \'2025-07-23 11:49:13\', \'2025-07-23 11:49:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432181\', \'106.7888084\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:49:13\', \'2025-07-23\', \'1753246153_b7184b8a026508a5ebb7.jpg\', \'2025-07-23 11:49:13\', \'2025-07-23 11:49:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 11:57:29 --> mysqli_sql_exception: Unknown column 'latitude' in 'field list' in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `at...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\laragon\www\apici\app\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert(Array)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#15 {main}
CRITICAL - 2025-07-23 11:57:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
[Method: POST, Route: api/attendance/checkin]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:57:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432011\', \'106.7888046\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:57:28\', \'2025-07-23\', \'1753246648_2227471011fbc8e705ec.jpg\', \'2025-07-23 11:57:28\', \'2025-07-23 11:57:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432011\', \'106.7888046\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:57:28\', \'2025-07-23\', \'1753246648_2227471011fbc8e705ec.jpg\', \'2025-07-23 11:57:28\', \'2025-07-23 11:57:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 11:57:29 --> [Caused by] mysqli_sql_exception: Unknown column 'latitude' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432011\', \'106.7888046\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:57:28\', \'2025-07-23\', \'1753246648_2227471011fbc8e705ec.jpg\', \'2025-07-23 11:57:28\', \'2025-07-23 11:57:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432011\', \'106.7888046\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:57:28\', \'2025-07-23\', \'1753246648_2227471011fbc8e705ec.jpg\', \'2025-07-23 11:57:28\', \'2025-07-23 11:57:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (\'1\', \'-6.3432011\', \'106.7888046\', \'MQ4Q+MC4, Gandul\', \'Shift 1 (07:00 - 15:00)\', \'WFO\', \'11:57:28\', \'2025-07-23\', \'1753246648_2227471011fbc8e705ec.jpg\', \'2025-07-23 11:57:28\', \'2025-07-23 11:57:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `attendances` (`user_id`, `latitude`, `longitude`, `address`, `shift`, `work_location_type`, `time_in`, `attendance_date`, `photo_in`, `created_at`, `updated_at`) VALUES (:user_id:, :latitude:, :longitude:, :address:, :shift:, :work_location_type:, :time_in:, :attendance_date:, :photo_in:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\api\Attendance.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\Attendance->checkin()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\Attendance))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
ERROR - 2025-07-23 12:02:48 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:03:37 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:04:04 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:05:46 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:09:45 --> mysqli_sql_exception: Table 'overtime_submissions' already exists in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `o...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `o...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `o...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `o...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-21-061759_CreateOvertimeSubmissionsTable.php(61): CodeIgniter\Database\Forge->createTable('overtime_submis...')
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateOvertimeSubmissionsTable->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:12:15 --> mysqli_sql_exception: Table 'presensicdgm.attendances' doesn't exist in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(772): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `at...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-22-032819_AddWorkTypeToAttendance.php(11): CodeIgniter\Database\Forge->addColumn('attendances', Array)
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddWorkTypeToAttendance->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:14:11 --> mysqli_sql_exception: Table 'presensicdgm.attendances' doesn't exist in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('ALTER TABLE `at...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `at...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `at...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\Forge.php(772): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `at...')
#4 E:\laragon\www\apici\app\Database\Migrations\2025-07-22-032819_AddWorkTypeToAttendance.php(11): CodeIgniter\Database\Forge->addColumn('attendances', Array)
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(876): App\Database\Migrations\AddWorkTypeToAttendance->up()
#6 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 E:\laragon\www\apici\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-07-23 12:56:30 --> mysqli_sql_exception: Table 'presensicdgm.overtime_submissions' doesn't exist in E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 E:\laragon\www\apici\vendor\codeigniter4\framework\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\laragon\www\apici\app\Controllers\api\OvertimeController.php(70): CodeIgniter\BaseModel->findAll()
#7 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Api\OvertimeController->history('1')
#8 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\OvertimeController))
#9 E:\laragon\www\apici\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\laragon\www\apici\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\laragon\www\apici\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 E:\laragon\www\apici\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('E:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2025-07-23 12:56:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'presensicdgm.overtime_submissions' doesn't exist
[Method: GET, Route: api/overtime/history/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = :user_id:
AND `start_date` >= :start_date:
AND `start_date` <= :start_date.1:
ORDER BY `start_date` DESC', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\api\OvertimeController.php(70): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\OvertimeController->history('1')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\OvertimeController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 12:56:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'presensicdgm.overtime_submissions' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = \'1\'
AND `start_date` >= \'2025-07-01\'
AND `start_date` <= \'2025-07-31\'
ORDER BY `start_date` DESC')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = \'1\'
AND `start_date` >= \'2025-07-01\'
AND `start_date` <= \'2025-07-31\'
ORDER BY `start_date` DESC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = :user_id:
AND `start_date` >= :start_date:
AND `start_date` <= :start_date.1:
ORDER BY `start_date` DESC', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\api\OvertimeController.php(70): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\OvertimeController->history('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\OvertimeController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
CRITICAL - 2025-07-23 12:56:30 --> [Caused by] mysqli_sql_exception: Table 'presensicdgm.overtime_submissions' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = \'1\'
AND `start_date` >= \'2025-07-01\'
AND `start_date` <= \'2025-07-31\'
ORDER BY `start_date` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = \'1\'
AND `start_date` >= \'2025-07-01\'
AND `start_date` <= \'2025-07-31\'
ORDER BY `start_date` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = \'1\'
AND `start_date` >= \'2025-07-01\'
AND `start_date` <= \'2025-07-31\'
ORDER BY `start_date` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `overtime_submissions`
WHERE `user_id` = :user_id:
AND `start_date` >= :start_date:
AND `start_date` <= :start_date.1:
ORDER BY `start_date` DESC', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\api\OvertimeController.php(70): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\OvertimeController->history('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\OvertimeController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('E:\\laragon\\www\\apici\\public\\index.php')
